### ISSUE TITLE
Scrum Report Sprint 2 (May 26 - June 8)

### ISSUE THREAD

**Issue by mingyugao** [achin797/tagify#10]

**Comment by mingyugao** [comment]
What did I work on?
- Set up repo with proper branches, meteor and react/redux
- Added ant design UI library
- Added react-router and attempted to set up client side routing
- Added authentication page UI

What were any major issues/challenges I ran into?
Setting up react-router, not sure which version is right, and how to use it with meteor.

What do I plan to work on for this coming iteration?
- Create a navbar component
- Create a home page (with navbar inside)

**Comment by akvaale** [comment]
What did you work on this past iteration (2 weeks)?
As planned in the previous scrum report, I researched capabilities of Spotify API and various React UI libraries. I came up with a design for the tag-button and song-list interface, inspired by the designs we sketched up in previous weeks. I have chosen a button library, and began working on the UI button elements. I have also began conceptually designing the interaction between tag-buttons and song-display.

What were any major issues/challenges you ran into?
In general, just working with meteor has been a bit confusing. No specific issues otherwise.

What do you plan to work on for this coming iteration (2 weeks)?
I will complete the front-end components "TagButton" and "SongDisplay," and implement the basic interaction between the two: Each TagButton will contain a unique Tag, and when toggled on, will display all Songs that also contain that same Tag.

**Comment by achin797** [comment]
What I did?
• Register the app with Spotify
• Setup up basic server and client for authentication

What were any major issues/challenges you ran into?
• Wrapping loginbuttons template into a react component and styling it. Still unable to do it.

What do you plan to work on for this coming iteration (2 weeks)?
• Wrap the login button template into a react component and style it with ant design.
• Configure spotify login to redirect to the homepage after successful login.
