### ISSUE TITLE
Scrum Report Sprint 3 (June 9 - 22)

### ISSUE THREAD

**Issue by akvaale** [achin797/tagify#22]

**Comment by akvaale** [comment]
What did you work on this past iteration (2 weeks)?
I completed the front-end components for "Homepage" which includes TagsPanel, SongList, Toggle buttons. These components utilize a reducer that I created; TagsPanel gets information from, and adds to the reducer. SongList retrieves information from the reducer and displays the corresponding songs.
Note: my changes were not in the project_3 branch. They are in the austin branch, and were committed the night before the due date. We weren't able to merge on time, so they were not in the demo.

What were any major issues/challenges you ran into?
Getting my toggle buttons working with the songlist added unique challenges. Specifically, dealing with duplicate songs, and songs appearing in multiple tags. I had to add a count function to my reducer to handle these occurrences. 

What do you plan to work on for this coming iteration (2 weeks)?
-Enter new tag form that pops up when clicking song on songlist
-Default view shows all songs, until a tag is selected
-If time permits, some backend work, in order to make the frontend work with the actual spotify API

**Comment by achin797** [comment]
**What I did**
• Implemented user authentication for our web app with spotify.
• Set up router to take user to the homepage after successful login.
• Set up Meteor methods responsible for interaction with the spotify api.

**What were any major issues/challenges you ran into?**
Trying to make accounts-ui work with ant-design components. Spent a lot of time on that. Learned that in this case it was better to just use meteor accounts instead of accounts-ui since we'd be able to customize it more, and it would make the styling easier which would also lead to cleaner code.

**What do you plan to work on for this coming iteration (2 weeks)?**
• Create the playlist page
• Populate the playlist page with data returned from spotify
• If time permits, add a condition to prevent user accessing home, tags and playlist pages when not logged in.

**Comment by mingyugao** [comment]
What did I work on?
- Create a navbar component
- Create a home page
- Create a tags page that allows the user to manage their tags

What were any major issues/challenges I ran into?
Adding react-router and figuring out how to use it properly. I had difficulty integrating that with the navigation components from our UI library. In the end I managed to resolve it by looking at the documentation of the two, googling and experimenting around with different approaches.

What do I plan to work on for this coming iteration?
- Code clean up & refactoring
- Update styles to be consistent
- Clean up reducer
- Link up the home page with the tags page (tags added from tags page should be displayed on home page)
