### ISSUE TITLE
Scrum Report Sprint 4 (June 23 - July 6)

### ISSUE THREAD

**Issue by mingyugao** [achin797/tagify#35]

**Comment by mingyugao** [comment]
What I did:
• refactor react components for home and tags page
• implement tag and filter features
• change tags page tags panel to use database

Major challenges I/we ran into
• linking the front and back end - I thought we would need to make HTTP requests, but it seems meteor has its own way of doing things

What I plan to do
• implement back end for managing user saved songs
• change home page to use database

**Comment by akvaale** [comment]
What I did:
- Create mongo collection to store user and tags
- Made endpoints to interact w/ DB -- add tag, remove tag, create/retrieve user
- Merge tags page to the rest of the code

Major challenges:
- I initially found it difficult to retrieve data -- my db was returning "undefined". I found a temporary workaround with fetch(), then Ming was ultimately able to find a cleaner solution. 
- Expected HTTP requests, but had to learn the alternative way that Meteor/mongo interact 

What I plan to do:
- Add taggedSongs object array to the database
- Use actual user SpotifyID for database purposes
- Import user's actual song library (instead of placeholders) -- cache this data on frontend

**Comment by achin797** [comment]
What I did:
• Implement endpoints for fetching user songs and playlists
• Converted HomePage into a class component

Major challenges I/we ran into
• Cleaning up the response sent by spotify

What I plan to do
• Render songs on the front end
• Implement cache for song library in order to avoid repeated api calls to spotify
